services:

  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "BDNRCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_RPC_ADDRESS: cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - bdnr

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-lacontraseñasecreta123}"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - bdnr

  backend:
    build: ./backend
    container_name: bdnr-backend
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
      neo4j:
        condition: service_started
    environment:
      # Cassandra: usar SIEMPRE el nombre del servicio docker como host
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: foros

      # Neo4j: también directo contra el servicio
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-lacontraseñasecreta123}
    networks:
      - bdnr


networks:
  bdnr:

volumes:
  neo4j_data:
  neo4j_logs:
  cassandra_data:
